### ISSUE TITLE
The changes in scenario, masterclass or project should be automatically get's reflected in it's preview

### ISSUE THREAD

**Issue by Burhanuddin-Nahargarwala** [enqurious/enqurious-platforms-bug-reporting#15] opened 2024-04-26 17:04 UTC
- In the current enqurious app (1.0), whatever changes we make in the project automatically get reflected in its preview. But in the enqurious 2.0, changes make in the content doesn't reflect in the preview

**Changes in content:**
Before Changes:
![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/105622461/6f4e9a3b-d3e5-436a-af14-b193d8c2a209)

After changes:
![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/105622461/0477e30c-b4bf-4027-baee-6932194b15a8)

**Preview**
Before changes and After changes
![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/105622461/2696d9c0-9e19-4cbf-91d3-0924024fbb97)

We need to refresh the page to get the changes in the preview.

[**Expected Result**: The changes should be automatically reflected in the preview without refreshing the page (like enqurious 1.0)]

**Comment by biku1998** [comment] 2024-04-26 17:17
It's a good to have feature not a bug. Closing this for now.

When refreshed the changes are reflected right? @Burhanuddin-Nahargarwala

**Comment by Burhanuddin-Nahargarwala** [comment] 2024-04-26 17:19
Yes, just mentioned it in the issue for further reference

**Closed** 2024-04-26 17:20 UTC
